### ISSUE TITLE
Wildcard * isn't working as expected

### ISSUE THREAD

**Issue by jofabian** [proginosko/LeechBlockNG#113]
Hello,
I wanted to block all ".cloud" sites like for example:
```
blah.cloud
download.cloud
```

So I added a rule like this:
`*.cloud`

It works for the examples but I noticed that it is also blocking me this site:
`blog.cloudflare.com`

I think that my rule shouldn't be blocking this last site. Am I wrong?

BTW I'm using LeechBlock NG (Next Generation) Version: 1.0.4 FireFox add-on.

**Comment by proginosko** [comment]
It isn't a bug, strictly speaking, but I admit that most users would find that behavior unexpected! 😃 

Basically, LB will block any URL that _begins_ with the pattern specified. So `somesite` on its own would block `somesite.com`, `somesite.org`, etc., and also `somesitesomewhere.com`, etc. Usually that isn't an issue because the patterns terminate in an unambiguous way (`somesite.com`, `somesite.org`, etc.). But yours is one of the exceptional cases.

The workarounds would be to either add a closing / or to use exceptions. So:

`*.cloud/`
or
`*cloud`
`+blog.cloudflare.com`

Hope this helps!

**Comment by jofabian** [comment]
I'll use the 1st workaround because it is more likely what I'm looking for.

Thank you for your answer!
