### ISSUE TITLE
Is there a way to block sites that do not contain specific words or phrases?

### ISSUE THREAD

**Issue by rpgdev** [proginosko/LeechBlockNG#120]
I know about: [https://www.proginosko.com/leechblock/faq/keywords/](https://www.proginosko.com/leechblock/faq/keywords/) but in my case I would like to allow some sites only if they contain specific words or phrases and block them otherwise. I tried adding some terms with a "+" prefix but that didn't work. Is there a way to implement this?

**Comment by Redevectored** [comment]
I didn't succeed, but to block every possible site, one can add 
*.* 
to the block set list and 
+github.com 
to add the simple exceptions so far. In the advanced options, there's a way to overwrite the exceptions with regular expressions, so maybe you'd like to explore those.

**Comment by proginosko** [comment]
Added in version 1.0.7. Use the option "Treat keywords as allow-conditions rather than block-conditions" under Advanced Options.

For example, if you want to block all Reddit pages that _don't_ contain the word 'sausage', enter the following as your list of sites...

`reddit.com`
`~sausage`

...and check the option above.
