### ISSUE TITLE
Counter seems to count down while computer is asleep

### ISSUE THREAD

**Issue by ssfrr** [proginosko/LeechBlockNG#122]
It seems that if a page is open when I shut my laptop (putting it to sleep) - the counter keeps counting down while the computer is asleep, so when I later open it up again the site is blocked immediately.

I just double checked by pulling up a site and checking the countdown timer, then closing my laptop for a minute, reopening it, and verifying that about a minute had elapsed on the timer.

**Comment by proginosko** [comment]
Hmm. That shouldn't be happening. Which OS are you using and which version of Firefox?

Is the option "Count time spent on these sites only when browser tab is active" selected?

**Comment by ssfrr** [comment]
Yep, I have that option checked. I'm using Arch Linux with the Gnome Shell environment (which uses Wayland, if that matters). Currently I'm using Firefox 69.0.

**Comment by proginosko** [comment]
Thanks. Does the countdown pause when you switch to another tab? Does it pause when you switch to another window (application)?

**Comment by ssfrr** [comment]
Yes, the timer pauses when I switch tabs within the browser, and also when I switch applications.

**Comment by proginosko** [comment]
Is this issue still occurring? It may have been fixed by changes in version 1.0.6.2. If not, reopen this issue.

**Comment by billwanjohi** [comment]
I'm experiencing the same behavior on LeechBlock NG 1.0.7.1 on Firefox 81.0.2-1 on Manjaro (Arch-based distro). Changing window focus or moving to a workspace in my window manager (i3) pauses the timer properly, but if I just suspend the machine while I'm on a blocked site, on resume, the timer subtracts the entire duration of sleep from my budget.

**Comment by proginosko** [comment]
Please try the following. Go to this test page I created:

https://www.proginosko.com/test/WindowFocusEvents.html

It simply shows when the web page gains/loses focus. Try switching to another window and back again. You should see a BLUR event followed by a FOCUS event. Refresh the page (to clear the log of events) and then suspend/unsuspend the machine. Are the BLUR and FOCUS events triggered?

**Comment by billwanjohi** [comment]
@proginosko as you say, when I change focus from and to that test window, I get BLUR and FOCUS events, respectively.

When I close my laptop lid, triggering a systemd-logind event that suspends my system (to RAM, not disk), and then I open my lid, waking the system, both while focused on your test page, no events are registered on the page.

When I instead manually suspend with the i3exit utility that I have bound to a keyboard shortcut, which calls a utility called `blurlock` followed by `systemctl suspend`, I get a few of state flips, and crucially, it stays in BLUR until I wake the machine back up by pressing the power button.

**Comment by proginosko** [comment]
Thanks, that's very helpful. So it sounds like the issue is a browser/system one that LB can't really overcome. If the browser isn't triggering the blur/focus events, then LB can't tell whether to count time or not.

Is the upshot of your last sentence that you have a workaround?

**Comment by billwanjohi** [comment]
I know _how_ to avoid this behavior (manually suspend, or just change focus before closing lid), but I still absentmindedly close it while on a web page all the time. Probably what I need to do is autostart a userland process that will subscribe to the systemd `suspend` event and rob Firefox of its focus. Will most likely start with `xss-lock`.

**Comment by billwanjohi** [comment]
Yes, it looks like by autostarting `xss-lock --transfer-sleep-lock -- i3exit lock` with my window manager, I get it to blur Firefox before suspending, preserving my sweet sweet procrastination time budget. Thank you for the diagnostic assistance!

**Comment by proginosko** [comment]
I'm going to close this issue because I'm concluding it's due to a issue for Firefox on Linux rather than a bug in LB.

**Comment by alexcanepa** [comment]
For what it's worth, I get the same issue on Firefox (84) for OSX (10.13). 
The linked test page shows a BLUR when I close my laptop lid and FOCUS when re-opening

**Comment by kubaello** [comment]
The same thing still happens with the latest version of LeechBlock for Firefox on Ubuntu 18.04.

Maybe a good solution would be to detect that the system was suspended by checking the delay since the last call to onInterval? If the delay is very long, then update all open/focus time counters as if all tabs had been closed when the previous tick happened and reopened/refocused right now. I suppose this check should be done in all event handlers, because any one of them can be the first to run after the system is resumed...

I might test this myself, but first I need to learn how to build a Firefox extension.

**Comment by kubaello** [comment]
It occurred to me, that if what I proposed works, a similar solution could be used to ignore apparent time changes caused by the user changing the system clock. I think the only necessary modification would be to also check if the delay is not negative.

Also, it might be better to check the delay since last call to any event handler. onInterval running every second is still important, as it limits the delay to 1 second (or slightly more if the machine is busy), but otherwise I don't think it needs any special tretment.
