### ISSUE TITLE
Can't see entire menu (Options)on Firefox Mobile

### ISSUE THREAD

**Issue by Espenol** [proginosko/LeechBlockNG#127]
Hello!
On my Huawei P20 Pro running LeechBlock I can't configure all settings as not all settings are visible. Specifically, the left part of the Options can not be viewed. I will illustrate with an image. 
![bilde](https://user-images.githubusercontent.com/17748952/69914548-f2fa2480-1445-11ea-981e-ae066b6f70eb.png)
On this image, I can not view anything to the left of what is viewed here. It does not allow me to scroll to the left. 

I tried to use Sync Storage to sync the settings but it is greyed out. If it had worked, this should nevertheless be fixed. 

Thank you for this very useful tool!

**Comment by proginosko** [comment]
On mobile devices you will often have to use landscape mode to view the options page.

Sync is not supported yet for Firefox on Android.

**Comment by Andrew5569** [comment]
The problem can be fixed by removing the `#form-container` styles in [options.css](https://github.com/proginosko/LeechBlockNG/blob/master/options.css#L87). However, this will make it so that the options are no longer centered on desktop. To fix this you can add the following to [options.css](https://github.com/proginosko/LeechBlockNG/blob/master/options.css). 

```css
#form {
  text-align: center;
}
```

**Comment by Flimm** [comment]
To give an update: Firefox for Android has now disabled installing extensions on Android, with the exception of a tiny number of extensions recommend by Mozilla. They have announced that they plan on expanding the list of extensions installable on Firefox for Android soon.
[
Mozilla recently announced (Sept 2020)](https://blog.mozilla.org/addons/2020/09/25/more-recommended-extensions-added-to-firefox-for-android-nightly/) that there adding a few more extensions to the list of extensions that can be installed on Firefox Nightly for Android. This includes LeechBlock NG. Soon, those extensions should be approved for Firefox for Android, too.

I personally am surprised that they added LeechBlock NG to this list, since the options are still difficult to use on a small screen. But I am glad that LeechBlock NG was added, as I really like this extension and am eagerly waiting to use it on Firefox for Android.
