### ISSUE TITLE
On Chrome, timer doesn't count if chrome window is not focused

### ISSUE THREAD

**Issue by BlooDCrescent** [proginosko/LeechBlockNG#133]
I use Google Chcrome 80.0.3987.116 on Windows 10 and I've setup a block set to block youtube.com. Leech block should allow 30 minutes of youtube every 12 hours and so it shows timer with countdown. But when browser windows loses focus (with youtube video still going on) the timer visibly stops after counting down last focused second and then stops. It beats the purpose of allowing any number of minutes.

**Comment by proginosko** [comment]
That's by design. If you want the timer to continue even when the window loses focus, deselect the option "Count time spent on these sites only when browser tab is active".

**Comment by Harfho** [comment]
When I switched tab also on chrome the countdown will stop but I want it to keep counting   cos I use to open so many tab , can the option 
 "Count time spent on these sites only when browser tab is active". solve this also .

**Comment by proginosko** [comment]
Yes, it should do.

**Comment by Harfho** [comment]
> Yes, it should do.

It does not work . it will strike through the waiting time.
![Untitled](https://user-images.githubusercontent.com/39716223/85203501-24fda600-b306-11ea-8e89-2e96431b8891.jpg)

**Comment by proginosko** [comment]
Sorry, we were talking past each other. This thread is about the countdown timer that appears in the corner of the page and shows how much time is left on a page/site before it is blocked.

You're talking about the delaying page countdown timer. It's designed to behave the way you describe. Otherwise, it defeats the purpose of the delay. You can just go to a delayed site, switch to another tab and browse away until the delay is complete, then go to the site. There's no penalty or disincentive in that case.
