### ISSUE TITLE
Countdown timer can be stoped clicking outside the browser (windows10 + Firefox)

### ISSUE THREAD

**Issue by sesshoumanu** [proginosko/LeechBlockNG#143]
The countdown timer can be stoped and you can continue scrooling the site by pasing the mouse over the browser (without clicking on it) and using the wheel. If you have two monitors, you can scroll the blocked site for an unlimited time (With the countdown timer stoped) by clicking anywhere in the second monitor and applying the same technique with the mouse wheel... you can still browse twitter and facebook this way  :)

btw.. thanks for this extension!

**Comment by noobymcnoob** [comment]
This actually stopped working in Firefox recently and was something I relied on.... Because I have a large monitor, I click off and do other work while Twitter is in the background. I use Twitter for work-related things so my time _in_ the tab is what is important. If I forget to change the tab before switching off, my time runs out which forces me to override which is against the point.

**Comment by proginosko** [comment]
Workaround: deselect the option "Count time spent on these sites only when browser tab is active" for the relevant block set.
