### ISSUE TITLE
Blocking forever does not work

### ISSUE THREAD

**Issue by mathiasj33** [proginosko/LeechBlockNG#15]
It seems that, with Leechblock NG, the option to block a set of sites until "the end of time" does not work anymore. Even if I specify the sites to be blocked from "0000-2400" from Monday to Sunday, they get unblocked after one week. When I try to access the site the extension says that I it will be unblocked in one week from now and after one week it does indeed get unblocked.

**Comment by proginosko** [comment]
Thanks for the report! I found (and fixed) the bug that caused the wrong end time to be shown (i.e., one week from now instead of "the end of time"). However, the sites should have been blocked 24/7 even if the blocking page didn't correctly show that. So I'm not sure why your sites got unblocked after one week.

Please keep an eye on it and let me know if you encounter the same error with the next release.
