### ISSUE TITLE
Delay Page not working for YouTube

### ISSUE THREAD

**Issue by Metaception** [proginosko/LeechBlockNG#17]
When the block list is set to NOT block only the first page, switching between YT videos does not seem to re-trigger LeechBlock. LeechBlock appears to believe that it is on the same page despite switching videos.

Pretty sure this is due the way YT handles switches videos, since instead of loading a new page, it seems to use JavaScript to replace parts instead.

Might be hard with the web-ext API to detect these kinda of changes.

**Comment by proginosko** [comment]
Can you give me a more specific example of "switching between YT videos" for me to test? Thanks.

**Comment by Metaception** [comment]
After the delay page loads the YT video, if you click on the Up Next video or any of the video suggestions on the right there is a red loading bar at the top of the page and the video switches.

**Comment by Yanim** [comment]
I think this issue could be extended to most of Youtube. For example if you block let's say **vsauce**, you can no longer access the channel by typing in "youtube.com/user/vsauce" in the address bar (as intended). However, if you just access the main youtube page "youtube.com" and search for vsauce in the youtube search field, you'll have no problem accessing the "youtube.com/user/vsauce" channel. This is probably due to the way youtube loads pages (I think it's called spf.js or something, I don't know anything about it though).

**Comment by proginosko** [comment]
Thanks for the extra info @Yanim. I have made some changes in v0.7 which might solve this issue. If not, we'll revisit the issue here.

**Comment by benburrill** [comment]
I believe this is still an issue.  When you click on youtube links within youtube the delay page doesn't appear.
