### ISSUE TITLE
Settings Page Randomly Resets to Blank 

### ISSUE THREAD

**Issue by RyanWalch** [proginosko/LeechBlockNG#18]
The setting page has reset for me twice since I switched over to LeechBlock NG at its release.  The site lists, names and times for my block list no longer appears and leechblock no longer blocks the original sites.  

I didn't have this problem on the old version.

**Comment by proginosko** [comment]
Thanks for the report. If you close all Firefox windows and restart Firefox, do your LeechBlock settings come back? Knowing that will help me track down the problem.

**Comment by Raphapere** [comment]
Same problem here! When I reset Firefox settings does not come back.

**Comment by RyanWalch** [comment]
Restarting didn't help.

**Comment by proginosko** [comment]
Okay, thanks for reporting that.

Well, the first thing you should do is export your options so you have a backup if/when this happens again!

The next time you discover the settings have disappeared, don't click either of the "Save Options" buttons, because that will ensure that your settings really are wiped. Instead, close all browser tabs/windows, restart Firefox, open the browser console (Ctrl+Shift+J), and then go to LB Options.

If the settings have reappeared, that tells me something useful. If they haven't, but there's an error message in the browser console, that may tell me something useful also! Either way, please report back any info here.

**Comment by proginosko** [comment]
This issue should be resolved in v0.7. If not, I will reopen it here.
