### ISSUE TITLE
BUG: Does not work ➜ Block youtube except some keyword

### ISSUE THREAD

**Issue by alerezaaa** [proginosko/LeechBlockNG#391]
Hi there, I use this extention for a while and its really good.  
but these is a problem

## explaination

I use a filter like this

```
youtube.com
~*cs50*
```

and also I checked "_Treat keywords as allow-conditions rather than block-conditions_" and I wonder that this addon open [youtube homepage](https://www.youtube.com/) (which obiviously this happens when there is a 'cs50' video in the homepage) BUT when I open a [link of cs50 video](https://www.youtube.com/watch?v=ywg7cW0Txs4) to watch it, this addon block the `watch` page (while there is a 'cs50' in the video title under the video player). MAYBE this addon does NOT check the headings!

I have noticed that when I open a link, this happens but when I click on the video in my homepage then move to the watching page, everything is okay BUT it maybe because of the "homepage not being blocked" and Leech block does not check followed page after openning the homeepage 🤔

please fix this problem  
Thanks in advance

**Comment by proginosko** [comment]
The issue here is that YouTube loads page content dynamically, but LB checks the _initial_ page content for keywords, so sometimes the keywords appear in the page too late for LB to catch them. This isn't a problem for _blocking_ by keyword, because LB keeps checking the page for keywords, so as soon as content with the keyword is loaded, the page is blocked. But it is a problem for _allowing_ by keyword, as in your case, because the page gets blocked before the content with the keyword is loaded. LB can't see into the future. 🙂

One solution would be for LB to check the title text for keywords as well (see #359). It looks like that would work for the scenario above. That would be very easy to implement.

Another solution would be to add an option to only check for keywords after a user-specified time (e.g., 2-3 seconds). This would allow time for the full page content to be loaded on sites like YouTube. That would take more work to implement, but it's doable.

**Comment by alerezaaa** [comment]
Thanks for your reply @proginosko 

Just one small note, I see the page loading and sometimes the keyword in the page and just after the page is being blocked. ( I mean, "the page is loading, the video box is not loaded yet, but page elements are loaded, (sometimes) I can see the title of video and some other elements under title is loaded and just after seeing them, page is getting blocked)

About dynamc load, so, how LB does not block youtube homepage? (youtube.com) while the dynamic loading is more obvious and takes more time (even sometimes, I must search through the page to find where is my keyword "cs50" in the homepage 😅)

I mentioned these two scenarios to clear the situation and if there is any kind of minor bugs, its being found 🙏

BTW, two solutions that you mentioned is very nice 👌

**Comment by proginosko** [comment]
I tested a version that checks the title as well as the body text, and it works for your scenario above. I will push it out in the next release.

> About dynamc load, so, how LB does not block youtube homepage?

I'm not sure what you mean here. When I enter the following...

```
youtube.com
~*cs50*
```

...the YouTube homepage is always blocked. If it's not blocked for you, it's most likely because 'cs50' appears somewhere in the text of the page (but possibly not as visible text). You can check by going to youtube.com (homepage), opening the browser console, and entering:

`document.body.innerText`

Perhaps copy the output to a text editor and search it for 'cs50'.
