### ISSUE TITLE
Override stopped working on about:addons

### ISSUE THREAD

**Issue by Torchpost** [proginosko/LeechBlockNG#396]
I have about:addons blocked but overrideable to inhibit myself from turning off the extension but not fully prevent it. I have done this for a couple of years and it has worked fine until yesterday. Override would not unblock it, even though it still worked for my other sets of overrideable sites.
   I logged into settings and set the block to "only non-private tabs" but it was still blocked in a private window. I then realized I had the url written in the "Use regular expression to match URLs to block (overrides list of sites)" field under Advanced Settings and deleted it, but now it doesn't block it even when the override is off.
   So I have a way around the issue, but I had someone else make the settings password, so it would be a hassle to make them log in every time I want to turn it on/off, so it would be preferable if I could fix it.

**Comment by proginosko** [comment]
Yes, this was a fix for issue #317, introduced in v1.6.2.

I think the expected behavior for most users is that override will apply only to the blocked sites, not to the "Prevent access" options. Otherwise the override feature just becomes a layover on the way to disabling the extension altogether.

I'm not sure I follow your second and third paragraphs. What do "it was still blocked" and "now it doesn't block it" refer to?

**Comment by smayer97** [comment]
as I just commented on #317, "As you can see by this latest issue, here, clearly there are scenarios that would warrant making it optional. I too have scenarios were that would be the desired, and preferred, way of functioning. 

Please consider this."

**Comment by Torchpost** [comment]
Okay, reading #317 did mostly clarify the issue.

As for what I was referring to in the second paragraph:
 - When "about:addons" was written in the "Use regular expression to match URLs to block (overrides list of sites)" field under advanced settings, I tried to unblock the set in private windows, but it remained blocked there.
 - When "about:addons" is only written in the main 'domain names of sites to block' field but not in the 'regular expression' field, the page is not blocked, even when the set is not overridden.
I did not have the "Prevent access to about:addons at times when these sites are blocked" box checked at any point, if that's relevant. And the third paragraph doesn't really matter. Sorry to be unclear.

**Comment by proginosko** [comment]
Okay, thanks.

To clarify:

1. You can't put "about:addons" in the "Use regular expression..." field unless it's formulated as a regular expression.
2. You can't put "about:addons" in the list of domain names, period, because it's not a domain name (like facebook.com).
3. The right way to block it is with the "Prevent access to about:addons..." option.

**Comment by smayer97** [comment]
Thanks for the change.
