### ISSUE TITLE
Unexpected behaviour of wildcard expressions

### ISSUE THREAD

**Issue by alistair-low** [proginosko/LeechBlockNG#426]
I have a block set with the following entries:

> `*.live`
> `*live.*`

I expected this to block sites such as:
* twickets.live
* glasgowlive.co.uk

but not:
* livecharts.co.uk

However, all three are blocked. So it seems that the expression doesn't have to match the whole domain name, only the start of it i.e. `*.live` is matching the start of the expanded `www.livecharts.co.uk`.

Is this a bug or the expected behaviour?

**Comment by proginosko** [comment]
It is expected behavior. Any URL that _begins_ with the given pattern will be blocked. That's typically what users expect, e.g., `twitter.com` will block `twitter.com/somepage` and so on.

You can avoid the behavior above by replacing `*.live` with `*.live/`.

For more fine-tuned blocking, you may have to resort to regular expressions (see under Advanced Options).

**Comment by alistair-low** [comment]
Good point, I didn't think of using the slash to match it correctly! Thanks - I'll close this now.
