### ISSUE TITLE
Leechblock Taking Up Firefox CPU Leading To Very Slow Loading

### ISSUE THREAD

**Issue by ScarfDyedShadow** [proginosko/LeechBlockNG#499]
Hello, I am a longtime user of Leechblock that has benefited tremendously from it, but as of recently my Firefox has been slowing down immensely, and I've pinned the issue down to Leechblock. As advised I have set it to process only active tabs, but that hasn't fixed the issue. I suspect the issue is that I have far too many exceptions designated in one of my block sets, probably more than Leechblock was intended to handle, and while I can rectify that I'd only like to do that if there's no other solution. I've attached my settings as a txt file. 
[LeechBlockOptions(1).txt](https://github.com/user-attachments/files/17499073/LeechBlockOptions.1.txt)

<img width="1390" alt="Screenshot 2024-10-23 at 6 15 32 PM" src="https://github.com/user-attachments/assets/64dfed97-c1ac-4a9c-ac5e-033f21eb1d7e">

**Comment by proginosko** [comment]
Yeah, this is almost certainly due to having multiple blocks with long lists of sites and/or exceptions. LB creates a regular expression to test the URL of the page loaded in the browser, and more complex regular expressions require more processing. One thing you could try is increasing the value of the option "Process tabs every __ second(s)" under General options.

**Comment by proginosko** [comment]
Closing this for now.
