### ISSUE TITLE
Regex for matching urls instead of wildcards.

### ISSUE THREAD

**Issue by lewisaronmilne** [proginosko/LeechBlockNG#9]
The current way of doing it is more limited. For example if I wanted to block youtube.com but not youtube.com/feed/subscriptions I would not be able to with the current system.

Regex would be work for this so it would be good to have as an option. Alternatively if there is a way to block the home page of a website but not all of it I would be interested in knowing it.

**Comment by proginosko** [comment]
Yes, you can do it as follows:

`youtube.com`
`+youtube.com/feed/subscriptions`

http://www.proginosko.com/leechblock/faq/exceptions/

**Comment by lewisaronmilne** [comment]
I've managed to work around it for youtube since there aren't many subdirectories (?) that I would need to use for that site (just /watch?etc... and /feed/subscriptions). 

But for sites that had a lot of them it gets a bit more finicky. 

e.g. reddit.com
I can't figure out a way to block reddit.com and reddit.com/r/all without blocking reddit.com/r/alloftherestofthem

**Comment by proginosko** [comment]
Okay, I see your point with the reddit.com example. One workaround in that particular case would be to use multiple block sets, since the blocks are applied sequentially. So, block set 1:

`reddit.com`
`+reddit.com/r/`

Then, block set 2:

`reddit.com/r/all`

If you're just blocking by time periods, that should work fine. If you're using time limits, it won't be ideal because each block set has its own time allowance.

I will think about allowing regexps in a future release (probably as an undocumented feature!).

**Comment by lewisaronmilne** [comment]
Thanks. It seems to be working great now.

**Comment by proginosko** [comment]
Okay, good. Are you using the workaround I suggested?

**Comment by lewisaronmilne** [comment]
Yes. I can use it for everything I want to block. I still think that having regex as an option would be a good idea though.

**Comment by Metaception** [comment]
I think it would be best to do it the same way userscripts handles URLs.

There is @match which limits what the wildcard operator supports.
Then there is @include which has full regex support.

Maybe you can toggle it with something like a per blocklist option?
I feel it would be better as a opt-in since regex is harder to debug and there is issue #7 on performance issues.

**Comment by proginosko** [comment]
How about a syntax like specifying a regex within slashes (e.g., /regex-goes-here/)?

**Comment by lewisaronmilne** [comment]
I think /'s are the right idea. Negation is already handled by a + sign.

**Comment by proginosko** [comment]
I've implemented this in version 0.8, but with separate options (under "Advanced Options"). It seemed like a cleaner way to do it. After playing around with some alternatives, I decided that allowing regexps in the site list would be too confusing and prone to user errors.

You can try the beta version if you like: https://addons.mozilla.org/en-US/firefox/addon/leechblock-ng/versions/beta

(If you do install the beta version, remember that you'll have to explicitly install the next release version to get back on the main release channel for auto-updates.)
