### ISSUE TITLE
constant I/O activity

### ISSUE THREAD

**Issue by JackSlaterIV** [proginosko/LeechBlockNG#95]
Dear James, first thank you very much for this great extension.
I noticed, on Firefox and Windows, that LB does constant I/O activity on the file \moz-extension+++80cb3081-a5f5-445e-9a07-307483a21537^userContextId=4294967295\idb\3647222921wleabcEoxlt-eengsairo.sqlite-wal.
I monitored this using Windows Performance Monitor, ticking on the "System" process, and it shows 7 KB/s constant writes.
Other than a lot of I/O, this also leads to fragmentation issues on non SSD drives.
Is this expected by design or can be improved? Thanks in advance.

**Comment by proginosko** [comment]
LB regularly writes to local storage (or sync storage, if selected) as it keeps track of the amount of time spent on sites in block sets. It does this so that the time data isn't lost if the user abruptly closes the browser (or the browser crashes!). That could account for the I/O activity.

That said, I'm running Firefox on Windows 10, and I don't see that kind of activity. Opening the Resource Monitor and reviewing the Firefox processes shows very little write activity to the LB local storage file, compared with other Firefox I/O activity. Also, I'm not sure why you think that file above is associated with LB, since the UUID in the filename is not LB's UUID.

**Comment by proginosko** [comment]
Follow-up: I'm aware that LB regularly writing to local storage is an issue and I'm working on an improvement.

**Comment by JackSlaterIV** [comment]
Thank you and sorry for the delay.
In the previous report I was using Firefox Developer.
I noticed that it works a little bit differently from the regular Firefox.
On Firefox Developer I see this options page URL for LeechBlock: moz-extension://80cb3081-a5f5-445e-9a07-307483a21537/options.html.
Instead, on standard Firefox the options page is located here: moz-extension://392dd10d-51a4-4f4f-a088-c7cee42b1ea3/options.html. And the file which is constantly accessed is this one:
profile\browser-extension-data\leechblockng@proginosko.com\storage.js.tmp

**Comment by proginosko** [comment]
Thanks, that's useful. Next release should resolve this issue.

**Comment by proginosko** [comment]
Version 0.9.10 adds an option for the user to specify how often time data is written to storage. (See under General tab.) Default is 10 seconds. Also, data is now only written when changed. These improvements should considerably reduce the I/O activity.
